### ISSUE TITLE
Unable to install columnify on MacOS w/ go get

### ISSUE THREAD

**Issue by eredi93** [reproio/columnify#55]
Following the README instructions, i'm trying to install columnify with go get. But i'm getting the following error: 
```
⇒  GO111MODULE=off go get github.com/reproio/columnify/cmd/columnify                                                                      
package github.com/vmihailenco/msgpack/v4: cannot find package "github.com/vmihailenco/msgpack/v4" in any of:
        /usr/local/Cellar/go/1.14.4/libexec/src/github.com/vmihailenco/msgpack/v4 (from $GOROOT)
        /Users/XXX/.go/src/github.com/vmihailenco/msgpack/v4 (from $GOPATH)
```

**Comment by t2y** [comment]
I had the same error with `GO111MODULE=off`. It seems that `GO111MODULE=on` can build columnify binary into $GOPATH.

```bash
$ GO111MODULE=on go get -v github.com/reproio/columnify/cmd/columnify
```

I found some issues in vmihailenco/msgpack repository. The author suggests using Go Modules.

* https://github.com/vmihailenco/msgpack/issues/237
* https://github.com/vmihailenco/msgpack/issues/251

**Comment by t2y** [comment]
I think this is README bug, so I will send PR.

**Comment by eredi93** [comment]
thanks @t2y 🙇

**Comment by Mohitp98** [comment]
**Worked for me-->**

1. Run go get github.com/vmihailenco/msgpack to install the master branch (v5) into your GOPATH.
2. cd ~/go/src/github.com/vmihailenco/msgpack
3. git checkout v4 to switch to the v4 branch
4. cd - to return back to the directory you were working in before.
5. When using HCL, import it still as github.com/vmihailenco/msgpack instead of as github.com/vmihailenco/msgpack/v4

These above steps resolved the import error for me~
